import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

import ThanksCardList from "@/components/thanks_card/list";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ThanksCard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1 className={styles.title}>
          Home
        </h1>
        <ThanksCardList />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
};

export default Home;
